import {
  doc,
  setDoc,
  type FirestoreError,
} from 'firebase/firestore';

import { db } from './firebase';
import { liveDoc } from './liveDoc';

// Fitur Book 📚 — daftar buku yang mau / lagi dibaca, dikelompokkan per tema.
//
// Daftar buku + daftar BAB tiap buku STATIK di sini (tidak masuk Firestore)
// supaya ringan & gratis. Yang disimpan ke Firestore hanya CENTANG per-bab,
// dalam SATU dokumen kecil biar sinkron antar perangkat:
//   users/{uid}/reading/books → { chapters: { [bookKey]: { [idxBab]: true } } }
// Sebuah buku dianggap "selesai" kalau semua babnya sudah dicentang.

export type BookCategory = { key: string; label: string };

export const BOOK_CATEGORIES: BookCategory[] = [
  { key: 'financial', label: '💵 Financial' },
  { key: 'mindset', label: '🧠 Mindset' },
  // Lima kategori di bawah = buku rujukan skill mingguan di fitur Learning 🎓,
  // mengikuti area skill-nya (lihat `bookKey` pada daftar SKILLS di
  // lib/learning.ts). Sejak 16 Sep 2026 SEMUA buku yang disebut di Skills ada
  // di sini, jadi kartu bukunya di Learning selalu bisa dibuka.
  { key: 'productivity', label: '💡 Produktivitas & Kreativitas' },
  { key: 'life', label: '🧰 Life Skills' },
  { key: 'science', label: '🌱 Sains & Lingkungan' },
  { key: 'tech', label: '💻 Teknologi & Digital' },
  { key: 'insight', label: '🌍 Wawasan' },
];

// free = teks lengkap gratis & legal (domain publik / kitab / esai penulis)
// info = halaman info resmi / ringkasan (buku berbayar — beli/pinjam bukunya)
export type BookLinkKind = 'free' | 'info';

export type Book = {
  key: string;
  category: string;
  title: string;
  author: string;
  year: number;
  info: string; // tentang apa & kenapa penting (Bahasa Indonesia)
  url: string;
  linkKind: BookLinkKind;
  chapters: string[]; // judul tiap bab — jadi checklist di halaman detail
};

// Urut per kategori: paling baru di atas (seperti daftar aslinya).
export const BOOKS: Book[] = [
  // ---------- 💵 Financial ----------
  {
    key: 'lords-easy-money',
    category: 'financial',
    title: 'The Lords of Easy Money',
    author: 'Christopher Leonard',
    year: 2022,
    info: 'Cara bank sentral (The Fed) mencetak uang murah dan dampaknya ke inflasi, aset, dan kesenjangan. Biar paham "kenapa harga naik terus".',
    url: 'https://www.google.com/search?q=The+Lords+of+Easy+Money+Christopher+Leonard+book',
    linkKind: 'info',
    // Buku ini bercerita mengikuti Thomas Hoenig; jumlah bab estimasi (bagi
    // per bab baca). Sesuaikan kalau kamu tahu daftar bab persisnya.
    chapters: [
      'Bab 1 · Going Below Zero',
      'Bab 2',
      'Bab 3',
      'Bab 4',
      'Bab 5',
      'Bab 6',
      'Bab 7',
      'Bab 8 · The Fixer',
      'Bab 9',
      'Bab 10',
      'Bab 11',
      'Bab 12',
      'Bab 13',
      'Bab 14',
      'Bab 15',
      'Bab 16',
      'Bab 17',
      'Bab 18',
    ],
  },
  {
    key: 'psychology-of-money',
    category: 'financial',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    year: 2020,
    info: 'Sukses finansial lebih soal perilaku daripada kepintaran. Sabar, rendah hati, dan hindari serakah lebih penting dari rumus investasi.',
    url: 'https://collabfund.com/blog/the-psychology-of-money/',
    linkKind: 'free',
    chapters: [
      "No One's Crazy",
      'Luck & Risk',
      'Never Enough',
      'Confounding Compounding',
      'Getting Wealthy vs. Staying Wealthy',
      'Tails, You Win',
      'Freedom',
      'Man in the Car Paradox',
      "Wealth is What You Don't See",
      'Save Money',
      'Reasonable > Rational',
      'Surprise!',
      'Room for Error',
      "You'll Change",
      "Nothing's Free",
      'You & Me',
      'The Seduction of Pessimism',
      "When You'll Believe Anything",
      'All Together Now',
      'Confessions',
    ],
  },
  {
    key: 'bitcoin-standard',
    category: 'financial',
    title: 'The Bitcoin Standard',
    author: 'Saifedean Ammous',
    year: 2018,
    info: 'Sejarah uang dari emas ke fiat, dan kenapa "uang keras" penting. Dasar untuk memahami Bitcoin secara ekonomi, bukan sekadar spekulasi.',
    url: 'https://en.wikipedia.org/wiki/The_Bitcoin_Standard',
    linkKind: 'info',
    chapters: [
      'Money',
      'Primitive Moneys',
      'Monetary Metals',
      'Government Money',
      'Money and Time Preference',
      "Capitalism's Information System",
      'Sound Money and Individual Freedom',
      'Digital Money',
      'What Is Bitcoin Good For?',
      'Bitcoin Questions',
    ],
  },
  {
    key: 'millionaire-master-plan',
    category: 'financial',
    title: 'The Millionaire Master Plan',
    author: 'Roger James Hamilton',
    year: 2014,
    info: 'Peta 9 level kekayaan bertahap, kenali posisimu sekarang lalu naik selangkah demi selangkah sesuai bakat alamimu.',
    url: 'https://www.google.com/search?q=The+Millionaire+Master+Plan+Roger+James+Hamilton+book',
    linkKind: 'info',
    // 9 level warna, dikelompokkan dalam 3 prisma (Foundation, Enterprise, Alchemy).
    chapters: [
      'Infrared · Prisma Foundation',
      'Red · Prisma Foundation',
      'Orange · Prisma Foundation',
      'Yellow · Prisma Enterprise',
      'Green · Prisma Enterprise',
      'Blue · Prisma Enterprise',
      'Indigo · Prisma Alchemy',
      'Violet · Prisma Alchemy',
      'Ultraviolet · Prisma Alchemy',
    ],
  },
  {
    key: 'zero-to-one',
    category: 'financial',
    title: 'Zero to One',
    author: 'Peter Thiel',
    year: 2014,
    info: 'Bikin sesuatu yang benar-benar baru (0→1), bukan meniru (1→n). Cara berpikir membangun bisnis/startup yang monopoli sehat.',
    url: 'https://en.wikipedia.org/wiki/Zero_to_One',
    linkKind: 'info',
    chapters: [
      'The Challenge of the Future',
      "Party Like It's 1999",
      'All Happy Companies Are Different',
      'The Ideology of Competition',
      'Last Mover Advantage',
      'You Are Not a Lottery Ticket',
      'Follow the Money',
      'Secrets',
      'Foundations',
      'The Mechanics of Mafia',
      'If You Build It, Will They Come?',
      'Man and Machine',
      'Seeing Green',
      "The Founder's Paradox",
    ],
  },
  {
    key: '4-hour-workweek',
    category: 'financial',
    title: 'The 4-Hour Workweek',
    author: 'Timothy Ferriss',
    year: 2007,
    info: 'Bekerja lebih cerdas: fokus (aturan 80/20), otomatisasi, dan delegasi supaya waktu & kebebasan lebih banyak, bukan sekadar sibuk.',
    url: 'https://tim.blog/',
    linkKind: 'info',
    // 4 langkah DEAL: Definition, Elimination, Automation, Liberation.
    chapters: [
      'Cautions and Comparisons',
      'Rules That Change the Rules',
      'Dodging Bullets (Fear-Setting)',
      'System Reset',
      'The End of Time Management',
      'The Low-Information Diet',
      'Interrupting Interruption',
      'Outsourcing Life',
      'Income Autopilot I: Finding the Muse',
      'Income Autopilot II: Testing the Muse',
      'Income Autopilot III: Management by Absence',
      'Disappearing Act: Escape the Office',
      'Beyond Repair: Killing Your Job',
      'Mini-Retirements',
      'Filling the Void',
    ],
  },
  {
    key: 'rich-dad-poor-dad',
    category: 'financial',
    title: 'Rich Dad Poor Dad',
    author: 'Robert Kiyosaki',
    year: 1997,
    info: 'Beda cara pikir soal uang: beli aset yang menghasilkan, pahami arus kas, dan melek finansial sejak dini.',
    url: 'https://en.wikipedia.org/wiki/Rich_Dad_Poor_Dad',
    linkKind: 'info',
    chapters: [
      'Rich Dad, Poor Dad',
      "Pelajaran 1: The Rich Don't Work for Money",
      'Pelajaran 2: Why Teach Financial Literacy?',
      'Pelajaran 3: Mind Your Own Business',
      'Pelajaran 4: Taxes and Corporations',
      'Pelajaran 5: The Rich Invent Money',
      'Pelajaran 6: Work to Learn, Not for Money',
      'Overcoming Obstacles',
      'Getting Started',
      'Still Want More? (To-Do List)',
    ],
  },
  {
    key: 'richest-man-babylon',
    category: 'financial',
    title: 'The Richest Man in Babylon',
    author: 'George S. Clason',
    year: 1926,
    info: 'Prinsip abadi lewat kisah Babilonia kuno: sisihkan minimal 10% penghasilan, kendalikan pengeluaran, dan uang bekerja untukmu.',
    url: 'https://archive.org/details/richestmaninbaby0000clas',
    linkKind: 'free',
    chapters: [
      'The Man Who Desired Gold',
      'The Richest Man in Babylon',
      'Seven Cures for a Lean Purse',
      'Meet the Goddess of Good Luck',
      'The Five Laws of Gold',
      'The Gold Lender of Babylon',
      'The Walls of Babylon',
      'The Camel Trader of Babylon',
      'The Clay Tablets from Babylon',
      'The Luckiest Man in Babylon',
    ],
  },
  // ---------- 🧠 Mindset ----------
  {
    key: 'book-of-proverbs',
    category: 'mindset',
    title: 'The Book of Proverbs (Amsal)',
    author: 'Vince Miller',
    year: 2023,
    info: 'Hikmat praktis untuk hidup, kerja, mulut, dan uang. Link menuju kitab Amsal (gratis), 31 pasal, cocok dibaca 1 pasal per hari.',
    url: 'https://alkitab.sabda.org/passage.php?passage=Amsal+1',
    linkKind: 'free',
    // 31 pasal — 1 pasal per hari.
    chapters: Array.from({ length: 31 }, (_, i) => `Pasal ${i + 1}`),
  },
  {
    key: 'deep-work',
    category: 'mindset',
    title: 'Deep Work',
    author: 'Cal Newport',
    year: 2016,
    info: 'Kemampuan fokus tanpa gangguan makin langka & bernilai. Cara melatih konsentrasi dalam untuk kerja bermutu tinggi.',
    url: 'https://www.calnewport.com/books/deep-work/',
    linkKind: 'info',
    chapters: [
      'Deep Work Is Valuable',
      'Deep Work Is Rare',
      'Deep Work Is Meaningful',
      'Aturan 1: Work Deeply',
      'Aturan 2: Embrace Boredom',
      'Aturan 3: Quit Social Media',
      'Aturan 4: Drain the Shallows',
    ],
  },
  {
    key: 'atomic-habits',
    category: 'mindset',
    title: 'Atomic Habits',
    author: 'James Clear',
    year: 2018,
    info: 'Perubahan 1% tiap hari yang menumpuk jadi besar. Sistem membangun kebiasaan baik & membuang yang buruk lewat langkah-langkah kecil.',
    url: 'https://jamesclear.com/atomic-habits',
    linkKind: 'info',
    chapters: [
      'The Surprising Power of Atomic Habits',
      'How Your Habits Shape Your Identity',
      'How to Build Better Habits in 4 Steps',
      'The Man Who Didn’t Look Right (Make It Obvious)',
      'The Best Way to Start a New Habit',
      'Motivation Is Overrated; Environment Matters',
      'The Secret to Self-Control',
      'How to Make a Habit Irresistible',
      'The Role of Family and Friends',
      'How to Find and Fix the Causes of Your Bad Habits',
      'Walk Slowly but Never Backward (Make It Easy)',
      'The Law of Least Effort',
      'How to Stop Procrastinating (Two-Minute Rule)',
      'How to Make Good Habits Inevitable',
      'The Cardinal Rule of Behavior Change (Make It Satisfying)',
      'How to Stick with Good Habits Every Day',
      'How an Accountability Partner Can Change Everything',
      'The Truth About Talent',
      'The Goldilocks Rule',
      'The Downside of Creating Good Habits',
    ],
  },
  // ---------- 💡 Produktivitas & Kreativitas ----------
  // Buku rujukan skill Learning (16 Sep 2026). Daftar bab diambil dari daftar
  // isi edisi yang disebut; kalau edisimu berbeda, tinggal disesuaikan.
  {
    key: 'critical-thinking',
    category: 'productivity',
    title: 'Critical Thinking: Tools for Taking Charge of Your Learning and Your Life',
    author: 'Richard Paul & Linda Elder',
    year: 2006,
    info: 'Alat berpikir jernih: membedah asumsi, standar berpikir, dan cara mengambil keputusan yang masuk akal, supaya tidak gampang termakan argumen yang cuma terdengar meyakinkan.',
    url: 'https://www.google.com/search?q=Critical+Thinking+Tools+for+Taking+Charge+of+Your+Learning+and+Your+Life+Paul+Elder',
    linkKind: 'info',
    // Edisi ke-2 (2006), 17 bab.
    chapters: [
      '1. Become a Fair-Minded Thinker',
      '2. The First Four Stages of Development: What Level of Thinker Are You?',
      '3. Self-Understanding',
      '4. The Parts of Thinking',
      '5. The Standards for Thinking',
      '6. Ask Questions That Lead to Good Thinking',
      '7. Master the Thinking, Master the Content',
      '8. Discover How the Best Thinkers Learn',
      '9. Redefine Grades as Levels of Thinking and Learning',
      '10. Make Decisions and Solve Problems',
      '11. Deal with Your Irrational Mind',
      '12. Monitor Your Sociocentric Tendencies',
      '13. Develop as an Ethical Reasoner',
      '14. Analyze and Evaluate Thinking in Corporate and Organizational Life',
      '15. Strategic Thinking: Part One',
      '16. Strategic Thinking: Part Two',
      '17. Becoming an Advanced Thinker: Our Conclusion',
    ],
  },
  {
    key: 'creative-habit',
    category: 'productivity',
    title: 'The Creative Habit',
    author: 'Twyla Tharp',
    year: 2003,
    info: 'Kreativitas itu kebiasaan, bukan bakat: ritual persiapan, "kotak" tiap proyek, dan latihan harian dari koreografer legendaris. Cocok buat yang merasa "aku bukan orang kreatif".',
    url: 'https://en.wikipedia.org/wiki/The_Creative_Habit',
    linkKind: 'info',
    chapters: [
      '1. I Walk into a White Room',
      '2. Rituals of Preparation',
      '3. Your Creative DNA',
      '4. Harnessing Your Memory',
      '5. Before You Can Think Out of the Box, You Have to Start with a Box',
      '6. Scratching',
      '7. Accidents Will Happen',
      '8. Spine',
      '9. Skill',
      '10. Ruts and Grooves',
      '11. An "A" in Failure',
      '12. The Long Run',
    ],
  },
  {
    key: 'how-to-win-friends',
    category: 'productivity',
    title: 'How to Win Friends and Influence People',
    author: 'Dale Carnegie',
    year: 1981,
    info: 'Cara membuat orang senang bekerja sama denganmu: tulus tertarik pada orang lain, jangan menang debat, dan hargai pendapat orang. Kitab klasik komunikasi & kepemimpinan (edisi revisi 1981).',
    url: 'https://en.wikipedia.org/wiki/How_to_Win_Friends_and_Influence_People',
    linkKind: 'info',
    chapters: [
      'Bagian 1 · 1. "If You Want to Gather Honey, Don\'t Kick Over the Beehive"',
      'Bagian 1 · 2. The Big Secret of Dealing with People',
      'Bagian 1 · 3. "He Who Can Do This Has the Whole World with Him"',
      'Bagian 2 · 1. Do This and You\'ll Be Welcome Anywhere',
      'Bagian 2 · 2. A Simple Way to Make a Good First Impression',
      'Bagian 2 · 3. If You Don\'t Do This, You Are Headed for Trouble',
      'Bagian 2 · 4. An Easy Way to Become a Good Conversationalist',
      'Bagian 2 · 5. How to Interest People',
      'Bagian 2 · 6. How to Make People Like You Instantly',
      'Bagian 3 · 1. You Can\'t Win an Argument',
      'Bagian 3 · 2. A Sure Way of Making Enemies, and How to Avoid It',
      'Bagian 3 · 3. If You\'re Wrong, Admit It',
      'Bagian 3 · 4. A Drop of Honey',
      'Bagian 3 · 5. The Secret of Socrates',
      'Bagian 3 · 6. The Safety Valve in Handling Complaints',
      'Bagian 3 · 7. How to Get Cooperation',
      'Bagian 3 · 8. A Formula That Will Work Wonders for You',
      'Bagian 3 · 9. What Everybody Wants',
      'Bagian 3 · 10. An Appeal That Everybody Likes',
      'Bagian 3 · 11. The Movies Do It. TV Does It. Why Don\'t You Do It?',
      'Bagian 3 · 12. When Nothing Else Works, Try This',
      'Bagian 4 · 1. If You Must Find Fault, This Is the Way to Begin',
      'Bagian 4 · 2. How to Criticize, and Not Be Hated for It',
      'Bagian 4 · 3. Talk About Your Own Mistakes First',
      'Bagian 4 · 4. No One Likes to Take Orders',
      'Bagian 4 · 5. Let the Other Person Save Face',
      'Bagian 4 · 6. How to Spur People On to Success',
      'Bagian 4 · 7. Give a Dog a Good Name',
      'Bagian 4 · 8. Make the Fault Seem Easy to Correct',
      'Bagian 4 · 9. Making People Glad to Do What You Want',
    ],
  },
  // ---------- 🧰 Life Skills ----------
  {
    key: 'first-aid-manual',
    category: 'life',
    title: 'First Aid Manual',
    author: 'St John Ambulance, St Andrew\'s First Aid & British Red Cross',
    year: 2021,
    info: 'Pedoman pertolongan pertama resmi (edisi ke-11): menilai korban, CPR, luka & pendarahan, patah tulang, tersedak, sampai kondisi darurat medis. Langkah demi langkah dengan gambar.',
    url: 'https://www.sja.org.uk/get-advice/first-aid-advice/',
    linkKind: 'info',
    // 13 bab edisi ke-11 (DK, 2021).
    chapters: [
      '1. Becoming a First Aider',
      '2. Managing an Incident',
      '3. Assessing a Casualty',
      '4. The Unresponsive Casualty',
      '5. Respiratory Problems',
      '6. Wounds and Circulation',
      '7. Bone, Joint, and Muscle Injuries',
      '8. Nervous System Problems',
      '9. Effects of Heat and Cold',
      '10. Foreign Objects, Poisoning, Bites, and Stings',
      '11. Medical Problems',
      '12. Techniques and Equipment',
      '13. Emergency First Aid',
    ],
  },
  {
    key: 'sas-survival-handbook',
    category: 'life',
    title: 'SAS Survival Handbook',
    author: 'John "Lofty" Wiseman',
    year: 2014,
    info: 'Buku survival paling terkenal di dunia dari mantan instruktur SAS: air, api, tempat berlindung, makanan, navigasi, membaca cuaca, sampai menghadapi bencana. Edisi ke-3.',
    url: 'https://en.wikipedia.org/wiki/SAS_Survival_Handbook',
    linkKind: 'info',
    // 11 bagian besar bukunya.
    chapters: [
      '1. Essentials',
      '2. Strategy',
      '3. Climate and Terrain',
      '4. Food',
      '5. Camp Craft',
      '6. Reading the Signs',
      '7. On the Move',
      '8. Health',
      '9. Survival at Sea',
      '10. Rescue',
      '11. Disasters',
    ],
  },
  {
    key: 'emotional-intelligence',
    category: 'life',
    title: 'Emotional Intelligence',
    author: 'Daniel Goleman',
    year: 1995,
    info: 'Kenapa EQ sering lebih menentukan daripada IQ: mengenali emosi sendiri, mengelolanya, memotivasi diri, berempati, dan menjaga hubungan. Buku yang mempopulerkan istilah EQ.',
    url: 'https://en.wikipedia.org/wiki/Emotional_Intelligence',
    linkKind: 'info',
    chapters: [
      'Bagian 1 · 1. What Are Emotions For?',
      'Bagian 1 · 2. Anatomy of an Emotional Hijacking',
      'Bagian 2 · 3. When Smart Is Dumb',
      'Bagian 2 · 4. Know Thyself',
      'Bagian 2 · 5. Passion\'s Slaves',
      'Bagian 2 · 6. The Master Aptitude',
      'Bagian 2 · 7. The Roots of Empathy',
      'Bagian 2 · 8. The Social Arts',
      'Bagian 3 · 9. Intimate Enemies',
      'Bagian 3 · 10. Managing with Heart',
      'Bagian 3 · 11. Mind and Medicine',
      'Bagian 4 · 12. The Family Crucible',
      'Bagian 4 · 13. Trauma and Emotional Relearning',
      'Bagian 4 · 14. Temperament Is Not Destiny',
      'Bagian 5 · 15. The Cost of Emotional Illiteracy',
      'Bagian 5 · 16. Schooling the Emotions',
    ],
  },
  // ---------- 🌱 Sains & Lingkungan ----------
  {
    key: 'the-gene',
    category: 'science',
    title: 'The Gene: An Intimate History',
    author: 'Siddhartha Mukherjee',
    year: 2016,
    info: 'Sejarah gen dari Mendel sampai CRISPR: bagaimana kita mewarisi sifat, lahirnya eugenika, terapi gen, dan pertanyaan etis yang menunggu di depan. Bekal memahami vaksin & kemajuan medis.',
    url: 'https://en.wikipedia.org/wiki/The_Gene:_An_Intimate_History',
    linkKind: 'info',
    // Dicentang per BAGIAN (enam bagian + prolog & epilog), bukan per bab:
    // babnya banyak & pendek-pendek.
    chapters: [
      'Prologue · Families',
      'Bagian 1 · The Missing Science of Heredity (1865–1935)',
      'Bagian 2 · In the Sum of the Parts, There Are Only the Parts (1930–1970)',
      'Bagian 3 · The Dreams of Geneticists (1970–2001)',
      'Bagian 4 · The Proper Study of Mankind Is Man (1970–2005)',
      'Bagian 5 · Through the Looking Glass (2001–2015)',
      'Bagian 6 · Post-Genome (2015–…)',
      'Epilogue · Bheda, Abheda',
    ],
  },
  {
    key: 'urban-farmer',
    category: 'science',
    title: 'The Urban Farmer',
    author: 'Curtis Stone',
    year: 2015,
    info: 'Bertani di lahan sempit perkotaan, dari halaman pinjaman sampai jadi usaha: memilih tanaman yang cepat panen, menyusun bedengan, dan menjual hasilnya ke restoran & pasar.',
    url: 'https://www.google.com/search?q=The+Urban+Farmer+Curtis+Stone+book',
    linkKind: 'info',
    // Jumlah bab estimasi (bagi per bab baca). Sesuaikan kalau kamu tahu
    // daftar bab persisnya.
    chapters: Array.from({ length: 24 }, (_, i) => `Bab ${i + 1}`),
  },
  {
    key: 'this-changes-everything',
    category: 'science',
    title: 'This Changes Everything: Capitalism vs. the Climate',
    author: 'Naomi Klein',
    year: 2014,
    info: 'Krisis iklim bukan cuma soal teknologi, tapi soal sistem ekonomi. Membongkar kenapa perubahan besar terus tertunda, dan gerakan akar rumput yang mulai mengubahnya.',
    url: 'https://en.wikipedia.org/wiki/This_Changes_Everything_(book)',
    linkKind: 'info',
    chapters: [
      'Introduction · One Way or Another, Everything Changes',
      'Bagian 1 · 1. The Right Is Right: The Revolutionary Power of Climate Change',
      'Bagian 1 · 2. Hot Money: How Free Market Fundamentalism Helped Overheat the Planet',
      'Bagian 1 · 3. Public and Paid For: Overcoming the Ideological Blockages to the Next Economy',
      'Bagian 1 · 4. Planning and Banning: Slapping the Invisible Hand, Building a Movement',
      'Bagian 1 · 5. Beyond Extractivism: Confronting the Climate Denier Within',
      'Bagian 2 · 6. Fruits, Not Roots: The Disastrous Merger of Big Business and Big Green',
      'Bagian 2 · 7. No Messiahs: The Green Billionaires Won\'t Save Us',
      'Bagian 2 · 8. Dimming the Sun: The Solution to Pollution Is... Pollution?',
      'Bagian 3 · 9. Blockadia: The New Climate Warriors',
      'Bagian 3 · 10. Love Will Save This Place: Democracy, Divestment, and the Wins So Far',
      'Bagian 3 · 11. You and What Army? Indigenous Rights and the Power of Keeping Our Word',
      'Bagian 3 · 12. Sharing the Sky: The Atmospheric Commons and the Power of Paying Our Debts',
      'Bagian 3 · 13. The Right to Regenerate: Moving from Extraction to Renewal',
      'Conclusion · The Leap Years',
    ],
  },
  // ---------- 💻 Teknologi & Digital ----------
  {
    key: 'digital-marketing-dummies',
    category: 'tech',
    title: 'Digital Marketing For Dummies',
    author: 'Ryan Deiss & Russ Henneberry',
    year: 2017,
    info: 'Peta lengkap pemasaran digital: perjalanan pelanggan, konten, landing page, iklan berbayar, email, SEO, media sosial, sampai mengukur hasilnya. Buat bisnis & karier ke depan.',
    url: 'https://www.google.com/search?q=Digital+Marketing+For+Dummies+Deiss+Henneberry',
    linkKind: 'info',
    // Daftar bab edisi pertama (2017). Sesuaikan kalau edisimu berbeda.
    chapters: [
      'Bagian 1 · 1. Understanding the Customer Journey',
      'Bagian 1 · 2. Choosing the Right Marketing Campaign',
      'Bagian 1 · 3. Crafting Winning Offers',
      'Bagian 2 · 4. Pursuing Content Marketing Perfection',
      'Bagian 2 · 5. Blogging for Business',
      'Bagian 2 · 6. Following Content Marketing Best Practices',
      'Bagian 3 · 7. Building High-Converting Landing Pages',
      'Bagian 3 · 8. Capturing Traffic with Search Marketing',
      'Bagian 3 · 9. Leveraging the Social Web',
      'Bagian 3 · 10. Tapping into Paid Traffic',
      'Bagian 3 · 11. Following Up with Email Marketing',
      'Bagian 4 · 12. Crunching Numbers: Running a Data-Driven Business',
      'Bagian 4 · 13. Optimizing Your Campaigns',
      'Bagian 5 · 14. The Ten Most Common Digital Marketing Mistakes',
      'Bagian 5 · 15. Ten Trending Digital Marketing Skills to Add to Your Resume',
      'Bagian 5 · 16. Ten Essential Tools for Digital Marketing Success',
    ],
  },
  // ---------- 🌍 Wawasan ----------
  // Buku-buku ini persis yang tertulis di daftar Skills-mu (Politics & Social),
  // jadi sekalian dimasukkan ke sini supaya bisa dicentang per bab dari fitur
  // Learning.
  {
    key: 'rule-of-law',
    category: 'insight',
    title: 'The Rule of Law',
    author: 'Tom Bingham',
    year: 2010,
    info: 'Apa arti "negara hukum" sebenarnya, dari hakim paling senior Inggris: hukum yang bisa diakses, setara untuk semua, dan mengikat penguasa. Dasar memahami hak kita sebagai warga negara.',
    url: 'https://en.wikipedia.org/wiki/The_Rule_of_Law_(book)',
    linkKind: 'info',
    chapters: [
      'Bagian I · 1. The Importance of the Rule of Law',
      'Bagian I · 2. Some History',
      'Bagian II · 3. The Accessibility of the Law',
      'Bagian II · 4. Law not Discretion',
      'Bagian II · 5. Equality Before the Law',
      'Bagian II · 6. The Exercise of Power',
      'Bagian II · 7. Human Rights',
      'Bagian II · 8. Dispute Resolution',
      'Bagian II · 9. A Fair Trial',
      'Bagian II · 10. The Rule of Law in the International Legal Order',
      'Bagian III · 11. Terrorism and the Rule of Law',
      'Bagian III · 12. The Rule of Law and the Sovereignty of Parliament',
      'Epilogue',
    ],
  },
  {
    key: 'sapiens',
    category: 'insight',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    year: 2011,
    info: 'Sejarah manusia dari kera biasa jadi penguasa bumi, lewat cerita bersama: uang, agama, negara, dan perusahaan. Modal dasar memahami cara kerja dunia hari ini.',
    url: 'https://www.ynharari.com/book/sapiens-2/',
    linkKind: 'info',
    chapters: [
      'Bagian 1 · 1. An Animal of No Significance',
      'Bagian 1 · 2. The Tree of Knowledge',
      'Bagian 1 · 3. A Day in the Life of Adam and Eve',
      'Bagian 1 · 4. The Flood',
      'Bagian 2 · 5. History’s Biggest Fraud',
      'Bagian 2 · 6. Building Pyramids',
      'Bagian 2 · 7. Memory Overload',
      'Bagian 2 · 8. There is No Justice in History',
      'Bagian 3 · 9. The Arrow of History',
      'Bagian 3 · 10. The Scent of Money',
      'Bagian 3 · 11. Imperial Visions',
      'Bagian 3 · 12. The Law of Religion',
      'Bagian 3 · 13. The Secret of Success',
      'Bagian 4 · 14. The Discovery of Ignorance',
      'Bagian 4 · 15. The Marriage of Science and Empire',
      'Bagian 4 · 16. The Capitalist Creed',
      'Bagian 4 · 17. The Wheels of Industry',
      'Bagian 4 · 18. A Permanent Revolution',
      'Bagian 4 · 19. And They Lived Happily Ever After',
      'Bagian 4 · 20. The End of Homo Sapiens',
    ],
  },
  {
    key: 'thinking-fast-and-slow',
    category: 'insight',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    year: 2011,
    info: 'Dua cara otak berpikir: cepat & otomatis vs lambat & teliti. Membongkar kenapa kita gampang termakan hoax, iklan, dan firasat yang keliru.',
    url: 'https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow',
    linkKind: 'info',
    chapters: [
      'I · 1. The Characters of the Story',
      'I · 2. Attention and Effort',
      'I · 3. The Lazy Controller',
      'I · 4. The Associative Machine',
      'I · 5. Cognitive Ease',
      'I · 6. Norms, Surprises, and Causes',
      'I · 7. A Machine for Jumping to Conclusions',
      'I · 8. How Judgments Happen',
      'I · 9. Answering an Easier Question',
      'II · 10. The Law of Small Numbers',
      'II · 11. Anchors',
      'II · 12. The Science of Availability',
      'II · 13. Availability, Emotion, and Risk',
      'II · 14. Tom W’s Specialty',
      'II · 15. Linda: Less is More',
      'II · 16. Causes Trump Statistics',
      'II · 17. Regression to the Mean',
      'II · 18. Taming Intuitive Predictions',
      'III · 19. The Illusion of Understanding',
      'III · 20. The Illusion of Validity',
      'III · 21. Intuitions vs. Formulas',
      'III · 22. Expert Intuition: When Can We Trust It?',
      'III · 23. The Outside View',
      'III · 24. The Engine of Capitalism',
      'IV · 25. Bernoulli’s Errors',
      'IV · 26. Prospect Theory',
      'IV · 27. The Endowment Effect',
      'IV · 28. Bad Events',
      'IV · 29. The Fourfold Pattern',
      'IV · 30. Rare Events',
      'IV · 31. Risk Policies',
      'IV · 32. Keeping Score',
      'IV · 33. Reversals',
      'IV · 34. Frames and Reality',
      'V · 35. Two Selves',
      'V · 36. Life as a Story',
      'V · 37. Experienced Well-Being',
      'V · 38. Thinking About Life',
    ],
  },
  {
    key: 'ethics-of-ambiguity',
    category: 'insight',
    title: 'The Ethics of Ambiguity',
    author: 'Simone de Beauvoir',
    year: 1947,
    info: 'Etika eksistensialis: kita bebas, tapi kebebasan itu selalu terikat dengan orang lain. Cara mengambil keputusan moral tanpa aturan siap pakai. Teks lengkapnya (terjemahan Inggris) gratis & legal.',
    url: 'https://www.marxists.org/reference/subject/ethics/de-beauvoir/ambiguity/',
    linkKind: 'free',
    chapters: [
      'I · Ambiguity and Freedom',
      'II · Personal Freedom and Others',
      'III · The Positive Aspect of Ambiguity: 1. The Aesthetic Attitude',
      'III · The Positive Aspect of Ambiguity: 2. Freedom and Liberation',
      'III · The Positive Aspect of Ambiguity: 3. The Antinomies of Action',
      'III · The Positive Aspect of Ambiguity: 4. The Present and the Future',
      'III · The Positive Aspect of Ambiguity: 5. Ambiguity',
      'Conclusion',
    ],
  },
];

// ===================== Progres baca per-bab =====================
// SATU dokumen kecil users/{uid}/reading/books —
//   { chapters: { [bookKey]: { [idxBab]: true } } }
// idxBab = indeks bab (0-based) dijadikan string oleh Firestore.

// bookKey → { idxBab → sudah dibaca }
export type ChaptersReadMap = Record<string, Record<string, boolean>>;

export function subscribeReadingProgress(
  uid: string,
  onChange: (chapters: ChaptersReadMap) => void,
  onError?: (error: FirestoreError) => void,
) {
  const ref = doc(db, 'users', uid, 'reading', 'books');
  return liveDoc(
    ref,
    (snapshot) => {
      onChange((snapshot.data()?.chapters as ChaptersReadMap) ?? {});
    },
    onError,
  );
}

/** Centang / hapus centang satu bab. Merge → bab lain tidak terganggu. */
export function setChapterRead(
  uid: string,
  bookKey: string,
  chapterIndex: number,
  read: boolean,
) {
  const ref = doc(db, 'users', uid, 'reading', 'books');
  return setDoc(
    ref,
    { chapters: { [bookKey]: { [chapterIndex]: read } } },
    { merge: true },
  );
}

/** Berapa bab buku ini yang sudah dicentang. */
export function chapterReadCount(
  chapters: ChaptersReadMap,
  book: Book,
): number {
  const map = chapters[book.key] ?? {};
  return book.chapters.reduce((n, _c, i) => (map[i] ? n + 1 : n), 0);
}

/** Buku dianggap selesai kalau SEMUA babnya sudah dicentang. */
export function isBookComplete(chapters: ChaptersReadMap, book: Book): boolean {
  return (
    book.chapters.length > 0 &&
    chapterReadCount(chapters, book) === book.chapters.length
  );
}
